### ISSUE TITLE
Does not return emails with custom labels

### ISSUE THREAD

**Issue by rlue** [tgray/contacts#11]
Email addresses labeled "Home", "Work", or "Other" appear when querying `contacts`:

![screen shot 2017-04-27 at 6 58 49 pm](https://cloud.githubusercontent.com/assets/12194123/25480556/c555da16-2b7b-11e7-9fa1-1cd78b725441.png)

    $ contacts alec
    NAME                  PHONE          IM                  EMAIL
    Alec Baldwin                                             alec@baldwin.com

But when a custom label is used, email addresses do not appear at all:

![screen shot 2017-04-27 at 6 59 32 pm](https://cloud.githubusercontent.com/assets/12194123/25480566/cbff1f9e-2b7b-11e7-84f7-51f89a330721.png)

    $ contacts alec
    NAME                  PHONE          IM                  EMAIL
    Alec Baldwin

**Comment by tgray** [comment]
I think this is for a different program.  Perhaps [http://gnufoo.org/contacts/](http://gnufoo.org/contacts/).

**Comment by rlue** [comment]
Oops. Sorry!
