### ISSUE TITLE
How to make an Xcode CLI tool?

### ISSUE THREAD

**Issue by ccorcos** [tgray/contacts#12]
Hey there, I'm just curious, how does this work? How do you create a commandline executable through Xcode?

**Comment by tgray** [comment]
Good question.  I'm not actually proficient in Obj-C or Xcode.  This was a very hacked together thing I did several years ago and I forget most of the details.  Some years ago they were called 'Foundation tools' if I recall correctly.  Whatever I did, it's in the Xcode project in the repository.  I haven't touched in a few years so I don't know what it looks like in the current version of macOS.

This [post](https://dev.to/ceri_anneblog/how-to-make-a-command-line-tool-in-xcode-2f81) looks like it has more updated information.
