### ISSUE TITLE
Getting contacts binary in the security and privacy allow list

### ISSUE THREAD

**Issue by MBuchaus** [tgray/contacts#4]
I'm getting 
contacts[7493]: __TCCAccessRequest_block_invoke48: Connection invalid
 in the log when trying to run contacts.. I believe it's due to the prog not being in the allow list in the security and privacy section on yosemite.  Might you or anyone have any insight into how to get the binary added to the list.. Drag and drop are not working. and the Google searches are not giving much.

**Comment by MBuchaus** [comment]
Ok I got it..  restarting iterm2 and then running the binary got the contacts prompt to work.. and allowed me to add iterm 2 to the list and now the command works.

**Comment by grantlucas** [comment]
I'm currently getting this issue when I use mutt within Tmux on Yosemite. :cry: Not sure how I can figure out what exactly is being disallowed in security settings. Both iTerm2 and Contacts are showing up and checked in the security list.

**Comment by tgray** [comment]
Minor update: I now have a new computer running 10.10.4.  I'm in the process of setting it up, mail being one of the first things, so I'll be revisiting this code in the next week or so.

**Comment by grantlucas** [comment]
Update on my situation: Turns out, in my setup, I was using Tmux to open mutt windows for me and I wasn't using reattach-user-namespace to initiate it in those instances. Apparently this worked fine under Mavericks but not under Yosemite. So, make sure, if mutt is being fired up under Tmux in any way, that reattach-user-namespace is used properly.

**Comment by tgray** [comment]
I have not tested contacts with tmux.  I like tmux but the whole reattach-user-namespace thing led me to stick with screen.  Glad to hear it's working fine.
