### ISSUE TITLE
Yosemite compatibility

### ISSUE THREAD

**Issue by tgray** [tgray/contacts#5]
Failed to get contacts from address book.
It seems utility doesn't work on Yosemite.

~/source/ploop$ contacts -v
contacts 0.2 (575f786)

Mac OS 10.10.3 (14D136)

----------

From an email.

**Comment by tksunw** [comment]
Contacts 0.1 is working for me on Yosemite.  I could try out 0.2 if you like.

    bash$ system_profiler -timeout 1 SPSoftwareDataType | grep "System Version"
      System Version: OS X 10.10.3 (14D136)

    bash$ contacts -l kennedy@sun.com
    Timothy.Kennedy@Sun.COM	Timothy Kennedy

    bash$ contacts -v
    contacts 0.1 (6f84d4d)

**Comment by tgray** [comment]
Minor update: I now have a new computer running 10.10.4.  I'm in the process of setting it up, mail being one of the first things, so I'll be revisiting this code in the next week or so.

**Comment by ligurio** [comment]
Any news? contacts still doesn't work for me.
Mac OS 10.10.3

**Comment by tgray** [comment]
So, contacts is currently running for me on 10.10.4.  I'm running contacts 0.2. I also just fired up contacts in Xcode and there seems to be no warnings or anything.

What errors are you getting?  Does it run fine in a terminal window, outside of screen or tmux?

**Comment by ligurio** [comment]
Bingo! The problem was in tmux which I use always in Terminal. When I executed contacts in without tmux it asked me about rights to access to Contacts.app (see https://yadi.sk/i/_IC2AQqhhwUky) and then it work as expected. contacts never asked me about access to Contacts.app earlier when I running it inside tmux.

**Comment by ligurio** [comment]
Was it known issue for 'contacts' utility?

**Comment by fgierlinger** [comment]
I had the same problem. Contacts would not give back any results inside a tmux session. I made it work by using the [reattach-to-user-namespace](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard]) utility.
