### ISSUE TITLE
Running contacts within tmux, needs documentation

### ISSUE THREAD

**Issue by neil-greenwood** [tgray/contacts#6]
If you run `contacts` within tmux, the connection to Contacts.app fails. `contacts` returns zero results with no error message.

There are problems with some applications running within tmux, I think it is related to the IPC mechanism of OS X.

An error message would be the best outcome.

**Comment by neil-greenwood** [comment]
OK, duplicate of issue #5 and issue #3.

This needs to be documented somewhere :)

**Comment by ligurio** [comment]
BTW ```reattach-to-user-namespace``` successfully resolves issue.
See https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard

**Comment by tgray** [comment]
Not a lot of documentation, but I added a note in the readme.  
[25e4c01](https://github.com/tgray/contacts/commit/25e4c0139727dbc49ebcad4fbde6ef0b7f6cda62)
